using System.Collections;
using NUnit.Framework;
using Unity.RecordedTesting;
using Unity.CloudTesting;
using UnityEngine.TestTools;

namespace GeneratedAutomationTests
{
    /// <summary>
    /// These tests were generated by Unity Automated QA for the recording: "Recordings/recording-2021-12-14-T04-03-03.json"
    /// You can regenerate this file from the Unity Editor Menu: Automated QA > Generate Recorded Tests
    /// </summary>
    public class Tests_recording_2021_12_14_T04_03_03 : RecordedTestSuite
    {
        /// <summary>
        /// Asserts that the recording can successfully play through to the end. 
        /// </summary>
        [UnityTest]
        [CloudTest]
        [RecordedTest("Recordings/recording-2021-12-14-T04-03-03.json")]
        public IEnumerator CanPlayToEnd()
        {
            yield return RecordedTesting.TestPlayToEnd();
            Assert.IsTrue(true);
        }
    }
}
